version: '3.5'
services:
  server:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    links:
      - mongo
    volumes:
      - .:/app
  mongo:
    image: mongo:4.0.10
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db